---
goss_version: 0.3.7

goss_dl_url: >-
  https://github.com/aelsabbahy/goss/releases/download/v{{ goss_version }}/goss-linux-amd64

goss_path: /usr/local/bin/goss

# dgoss

goss_dgoss_dl_url: >-
  https://github.com/aelsabbahy/goss/releases/download/v{{ goss_version }}/dgoss

goss_dgoss_path: /usr/local/bin/dgoss
