---
- name: Verifica se doctl {{ doctl_version }} estÃ¡ instalado
  shell: doctl version || true
  register: doctl_check
  changed_when: false

- name: Instala doctl
  unarchive:
    remote_src: true
    src: "{{ doctl_dl_url }}"
    dest: "{{ doctl_path | dirname }}"
    owner: root
    group: root
    mode: 0755
  when: >
    doctl_check.stdout_lines | length == 0
    or doctl_version not in doctl_check.stdout_lines[0]

- name: Configura Bash completion
  shell: doctl completion bash > /etc/bash_completion.d/doctl
  changed_when: false
  when: >
    doctl_check.stdout_lines | length == 0
    or doctl_version not in doctl_check.stdout_lines[0]
