---
# NOTE: it seems that "state: absent" behaviour is buggy for xfconf module,
#       so we run "xfconf-query" directly.
- name: Remove atalhos do teclado selecionados
  command: >
    xfconf-query --channel xfce4-keyboard-shortcuts --property '/commands/custom/{{ item }}' --reset
  loop: "{{ desktop_remove_shortcuts }}"
  changed_when: false

- name: Configura atalhos do teclado
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: /commands/custom/{{ item.shortcut }}
    value: "{{ item.cmd }}"
    value_type: string
    state: present
  loop: "{{ desktop_shortcuts }}"
  when: item.shortcut not in desktop_remove_shortcuts
