---
- name: Verifica se aws-vault {{ awsvault_version }} estÃ¡ instalado
  ansible.builtin.shell: aws-vault --version || true
  register: awsvault_check
  changed_when: false

- name: Instala aws-vault
  ansible.builtin.get_url:
    url: "{{ awsvault_dl_url }}"
    dest: "{{ awsvault_path }}"
    force: true
    owner: root
    group: root
    mode: "0755"
  when: >
    awsvault_check.stderr_lines | length == 0
    or awsvault_version not in awsvault_check.stderr_lines[0]

- name: Instala Bash completion
  ansible.builtin.get_url:
    url: "{{ awsvault_completion_url }}"
    dest: /etc/bash_completion.d/aws-vault
    force: true
    owner: root
    group: root
    mode: "0644"
  when: >
    awsvault_check.stderr_lines | length == 0
    or awsvault_version not in awsvault_check.stderr_lines[0]
  tags: awsvault:completion
