---
- name: Cancela se arquitetura do sistema não for x64
  fail:
    msg: >
      Fatal: o Chrome 32 bits foi descontinuado para o Linux em Março de 2016.
      Desculpe, seu sistema não é compatível.
      Dica: o Chromium ainda é uma opção para sistemas 32 bits.
  when: ansible_architecture != "x86_64"

# O Chrome é instalado via download direto do .deb porque ele mantém um cron
# ("/opt/google/chrome/cron/google-chrome") que manipula diretamente o arquivo
# "/etc/apt/sources.list.d/google-chrome.list". Logo, prefiro não manipular
# a configuração do repositório pelo Ansible.

- name: Verifica se Chrome está instalado
  shell: dpkg-query --show google-chrome-stable || true
  register: chrome_check
  changed_when: false

# Tarefas de instalação
- include: install-deb.yml
  when: "'no packages found matching' in chrome_check.stderr"

# O Chrome sobrepõe os padrões dos alternatives '*-www-browser'
# (aparentemente ele se considera o último biscoito do pacote).
- name: Configura alternatives de '*-www-browser' para o Firefox
  alternatives:
    name: "{{ item }}"
    path: /usr/bin/firefox
  with_items:
    - gnome-www-browser
    - x-www-browser
