---
- name: Verifica se terraform-docs {{ terraform_docs_version }} estÃ¡ instalado
  shell: terraform-docs --version || true
  register: terraform_docs_check
  changed_when: false

- name: Instala terraform-docs
  get_url:
    url: "{{ terraform_docs_dl_url }}"
    dest: "{{ terraform_docs_path }}"
    force: yes
    owner: root
    group: root
    mode: 0755
  when: >
    terraform_docs_check.stdout_lines | length == 0
    or terraform_docs_version not in terraform_docs_check.stdout_lines[0]
