---
- name: Configura swappiness
  sysctl:
    name: vm.swappiness
    value: "10"
    sysctl_file: /etc/sysctl.d/90-ansible-workstation.conf
    state: present
    reload: true
  tags: base-system:sysctl

- name: Configura porta do SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^Port "
    line: "Port {{ base_ssh_port }}"
    validate: "sshd -t -f %s"
  notify: Reinicia SSH
  tags: base-system:ssh

- name: Desativa usuário Guest do LightDM
  copy:
    content: |
      [Seat:*]
      allow-guest=false
    dest: /etc/lightdm/lightdm.conf.d/50-no-guest.conf
    owner: root
    group: root
    mode: 0644
  tags: base-system:lightdm

- name: Configura tamanho máximo de logs do Journal (systemd)
  ini_file:
    path: /etc/systemd/journald.conf
    section: Journal
    option: SystemMaxUse
    value: "{{ base_journald_system_max_use }}"
    create: false
    backup: true
    state: present
  notify: Reinicia systemd-journald
  tags: base-system:journald

- name: Cria diretório de configurações do XOrg
  file:
    path: /etc/X11/xorg.conf.d
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: base-system:xorg

- name: Configura anti-tearing para placa gráfica Intel
  copy:
    src: xorg/intel.conf
    dest: /etc/X11/xorg.conf.d/20-intel.conf
    owner: root
    group: root
    mode: 0644
  tags: base-system:xorg

- name: Habilita insultos do sudo
  copy:
    content: |
      Defaults  insults
    dest: /etc/sudoers.d/insults
    owner: root
    group: root
    mode: 0440
    validate: "visudo -cf %s"
  tags: base-system:sudo

- name: Configura comportamento do Num Lock
  lineinfile:
    path: /etc/default/numlockx
    regexp: "^NUMLOCK=.*$"
    line: "NUMLOCK=keep"
    owner: root
    group: root
    mode: 0644
    create: false
  tags: base-system:numlock
