---
awscli_version: 1.18.57

awscli_install_dir: /opt/awscli

awscli_symlink_dir: /usr/local/bin

awscli_enable_bash_completion: true

# aws-shell

awscli_install_shell: true

awscli_shell_install_dir: /opt/aws-shell

awscli_shell_version: 0.2.1
