---
- name: Cria diretório de autostart
  file:
    path: "{{ desktop_autostart_dir }}"
    state: directory
    owner: "{{ desktop_user }}"
    group: "{{ desktop_user }}"

- name: Desativa inicialização automática dos aplicativos definidos
  copy:
    content: |
      [Desktop Entry]
      Hidden=true
    dest: "{{ desktop_autostart_dir }}/{{ item }}.desktop"
    owner: "{{ desktop_user }}"
    group: "{{ desktop_user }}"
  loop: "{{ desktop_autostart_disable_apps }}"
  become: true
  become_user: "{{ desktop_user }}"
